---
dependency:
  name: galaxy
driver:
  name: delegated
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: macos-1014-dev
provisioner:
  name: ansible
  inventory:
    host_vars:
      macos-1014-dev:
        ansible_python_interpreter: "/usr/bin/python"
verifier:
  name: testinfra
