---
- hosts: ubuntu1604
  tasks:
    - name: Enable https for apt
      apt:
        name: apt-transport-https

- hosts: ubuntu1804
  tasks:
    - name: Install gpg
      apt:
        name: gpg
        update_cache: true
