---
jobs:
  release:
    env:
      GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Release
        uses: cycjimmy/semantic-release-action@v2.1.3
        with:
          branch: master
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git@8.0.0
name: Release
on:
  push:
    branches:
      - master
